const BOARD = {
  FETCH_REQUEST: "FETCH_REQUEST",
  FETCH: "FETCH_BOARD",
  CREATE_REQUEST: "CREATE_BOARD_REQUEST",
  CREATE_FAIL: "CREATE_FAIL",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  UPDATE_BOARD: "UPDATE_BOARD",
  UPDATE_BOARD_SUCCESS:'UPDATE_BOARD_SUCCESS',
  UPDATE_BOARD_FAILURE :'UPDATE_BOARD_FAILURE',
  FETCH_BOARD_DATA: "FETCH_BOARD_DATA",
  CHANGE_VISIBLE_ADD: "CHANGE_VISIBLE_ADD",
  ADD_CARD_REQUEST: "ADD_CARD_REQUEST",
  ADD_CARD_SUCCESS: "ADD_CARD_SUCCESS",
  ADD_CARD_FAILURE: "ADD_CARD_FAILURE",
  ADD_CARD_CANCEL_REQUEST:'ADD_CARD_CANCEL_REQUEST',
  UPDATE_CARD:'UPDATE_CARD',
  DELETE_CARD:'DELETE_CARD',
  DELETE_CARD_FAIL:"DELETE_CARD_FAIL"
};

export default BOARD;
