const USER = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGIN_OAUTH:'USERS_LOGIN_OAUTH',
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    LOGOUT:"USERS_REQUEST",
    EDIT_REQUEST:'EDIT_REQUEST',
    EDIT_DONE:'EDIT_DONE'
}

export default USER